source :rubygems

# Photo uploads
gem 'aws-sdk'
gem "paperclip", "~> 3.0"

# Templating engine
gem 'haml'

# PostgreSQL driver
gem 'pg'

# Sinatra driver
gem 'sinatra'
gem 'sinatra-contrib'

# Use Thin for our web server
gem 'thin'

gem 'activesupport'
gem 'activerecord'

gem 'rake'

gem 'shotgun'

group :test do
  gem 'faker'
  gem 'rspec'
end
