source :rubygems

# Photo uploads
gem 'carrierwave'
gem 'mini_magick'
gem "fog", "~> 1.3.1"

# Templating engine
gem 'haml'

# PostgreSQL driver
gem 'pg'

# Sinatra driver
gem 'sinatra'
gem 'sinatra-contrib'

# Use Thin for our web server
gem 'thin'

gem 'activesupport'
gem 'activerecord'

gem 'rake'

gem 'shotgun'

group :test do
  gem 'faker'
  gem 'rspec'
end
